# Generated by Django 3.1.7 on 2021-03-25 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210311_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image_profile',
            field=models.ImageField(default='media/yam.jpg', upload_to=''),
        ),
    ]
