# Generated by Django 3.1.7 on 2021-03-25 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210325_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='image_profile',
            new_name='image',
        ),
    ]
