# Generated by Django 3.1.7 on 2021-05-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210529_0137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rank',
        ),
    ]
