# Generated by Django 3.2.4 on 2021-06-26 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email_active',
        ),
    ]
