# Generated by Django 3.2.4 on 2021-06-26 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_email_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
