# Generated by Django 3.1.7 on 2021-03-14 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='center',
            table='center',
        ),
    ]
