# Generated by Django 3.1.7 on 2021-03-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0004_errorlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorlist',
            name='email',
            field=models.EmailField(max_length=64),
        ),
    ]
