# Generated by Django 3.1.7 on 2021-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0005_auto_20210322_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='center',
            name='area',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
